FROM registry.cn-shanghai.aliyuncs.com/wmn/cuda:3.6.10-slim

RUN pip3 install dask[complete]

ENV PIP_SUFFIX=" -i http://mirrors.cloud.aliyuncs.com/pypi/simple/ --trusted-host mirrors.cloud.aliyuncs.com"

