apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
  creationTimestamp: '2020-02-17T07:02:23Z'
  generation: 6
  labels:
    app: dask
  name: dask-worker
  namespace: default
  resourceVersion: '227237445'
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/dask-worker
  uid: 727a5273-5153-11ea-871d-16bfbe3ae69c
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dask
      component: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        component: worker
    spec:
      containers:
        - args:
            - 'dask-headless-service:8786'
            - '--nthreads'
            - '2'
          command:
            - dask-worker
          image: 'registry-vpc.cn-shanghai.aliyuncs.com/wmn/cuda:gp-mining'
          imagePullPolicy: IfNotPresent
          name: dask-worker
          resources:
            requests:
              cpu: '2'
              memory: 8Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /cache-test
              name: cache-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: pvc-nas
status:
  conditions:
    - lastTransitionTime: '2020-02-17T07:27:18Z'
      lastUpdateTime: '2020-02-17T07:27:18Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-02-17T07:02:23Z'
      lastUpdateTime: '2020-02-17T08:55:49Z'
      message: ReplicaSet "dask-worker-6765d94764" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 6
