apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: dask
  name: dask-scheduler
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dask
      component: scheduler

  template:
    metadata:
      labels:
        app: dask
        component: scheduler
    annotations:

    spec:
      containers:
        - command:
            - dask-scheduler
          image: 'registry-vpc.cn-shanghai.aliyuncs.com/wmn/alpha:dask-cuda-jupyter'
          imagePullPolicy: IfNotPresent
          name: dask-scheduler
          workingDir: /
          ports:
            - containerPort: 8786
              name: scheduler-port
              protocol: TCP
            - containerPort: 8787
              name: dashboard-port
              protocol: TCP
            - containerPort: 8888
                name: jupyter-port
                protocol: TCP
          resources:
            requests:
              cpu: '2'
              memory: 8Gi
          volumeMounts:
            - mountPath: /mnt/nas
              name: nas
      volumes:
        - name: nas
          persistentVolumeClaim:
            claimName: pvc-nas