apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: dask
  name: dask-scheduler
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dask
      component: scheduler
  template:
    metadata:
      labels:
        app: dask
        component: scheduler
      annotations:
        #      k8s.aliyun.com/eci-instance-type: ecs.gn5i-c4g1.xlarge
        k8s.aliyun.com/eci-image-snapshot-id: imc-uf67to9g9fsy6t2veqmz
    spec:
      containers:
        - args:
            - 'start.sh'
          command:
            - sh
          image: 'registry-vpc.cn-shanghai.aliyuncs.com/wmn/alpha:lightgbm-gpu'
          imagePullPolicy: IfNotPresent
          name: dask-scheduler
          workingDir: /
          ports:
            - containerPort: 8786
              name: scheduler-port
              protocol: TCP
            - containerPort: 8787
              name: dashboard-port
              protocol: TCP
            - containerPort: 8888
              name: jupyter-port
              protocol: TCP
          resources:
            requests:
              cpu: '2'
              memory: 8Gi
          volumeMounts:
            - mountPath: /mnt/nas
              name: nas
      volumes:
        - name: nas
          persistentVolumeClaim:
            claimName: pvc-nas
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: dask
  name: dask-cpu-worker
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dask
      component: worker
  template:
    metadata:
      labels:
        app: dask
        component: worker
    annotations:
      k8s.aliyun.com/eci-image-snapshot-id: imc-uf6hngjb4a32puhs5v7v
    #      k8s.aliyun.com/eci-instance-type: ecs.gn5i-c4g1.xlarge
    spec:
      containers:
        - args:
            - 'dask-headless-service:8786'
            - '--nthreads'
            - '2'
          command:
            - dask-worker
          image: 'registry-vpc.cn-shanghai.aliyuncs.com/wmn/alpha:dask-jupyter'
          imagePullPolicy: IfNotPresent
          name: dask-worker
          #          resources:
#            requests:
#              cpu: '2'
#              memory: 8Gi
          volumeMounts:
            - mountPath: /mnt/nas
              name: nas
      volumes:
        - name: nas
          persistentVolumeClaim:
            claimName: pvc-nas
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: dask
  name: dask-gpu-worker
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dask
      component: worker
  template:
    metadata:
      labels:
        app: dask
        component: worker
      annotations:
        #        k8s.aliyun.com/eci-gpu-type: "P4"
        k8s.aliyun.com/eci-instance-type: "ecs.gn5-c8g1.2xlarge"
        k8s.aliyun.com/eci-image-snapshot-id: imc-uf67to9g9fsy6t2veqmz
    spec:
      containers:
        - args:
            - 'dask-headless-service:8786'
            - '--nprocs'
            - '1'
          command:
            - dask-worker
          image: 'registry-vpc.cn-shanghai.aliyuncs.com/wmn/alpha:lightgbm-gpu'
          imagePullPolicy: Always
          name: dask-worker
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /mnt/nas
              name: nas
      volumes:
        - name: nas
          persistentVolumeClaim:
            claimName: pvc-nas