apiVersion: v1
kind: Service
metadata:
  metadata:
    labels:
      app: dask
  namespace: default
  name: dask-headless-service
spec:
  clusterIP: None
  ports:
    - port: 8786
      protocol: TCP
      targetPort: 8786
  selector:
    app: dask
    component: scheduler
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dask
  name: dask-service
  namespace: default
spec:
  ports:
    - name: scheduler-port
      nodePort: 31596
      port: 8787
      protocol: TCP
      targetPort: 8787
    - name: dashboard-port
      nodePort: 31825
      port: 8786
      protocol: TCP
      targetPort: 8786
    - name: jupyter-port
      nodePort: 32287
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: dask
    component: scheduler
  type: LoadBalancer