apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  annotations:
    "virtual-kubelet.io/gpu-type": "T4"
spec:
  containers:
    - image: registry-vpc.cn-shanghai.aliyuncs.com/wmn/cuda:10.0-devel-ubuntu18.04 # 训练任务的镜像
      name: cuda-10.0
      command:
        - "sleep"
      args:
        - "3600"
      resources:
        limits:
          "nvidia.com/gpu": "1"
        resources:
          requests:
            cpu: 2
            memory: 8Gi


