apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jupyterlab
  labels:
    app: jupyterlab
spec:
  replicas: 0
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    annotations:
      k8s.aliyun.com/eci-image-cache: "true"
    spec:
      containers:
        - args:
            - 'lab'
            - '--allow-root'
            - '--ip'
            - '0.0.0.0
          command:
            - jupyter
          image: 'registry-vpc.cn-shanghai.aliyuncs.com/wmn/cuda:data-routine'
          workingDir: /mnt/nas
          imagePullPolicy: IfNotPresent
          name: jupyterlab
          resources:
            requests:
              cpu: '2'
              memory: 8Gi
          ports:
            - containerPort: 8888
              name: jupyter-server
              protocol: TCP
          volumeMounts:
            - mountPath: /mnt/nas
              name: pvc-nas

      volumes:
        - name: pvc-nas
          persistentVolumeClaim:
            claimName: pvc-nas
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyterlab
  name: jupyterlab-svc

spec:
  ports:
    - name: jupyter-server
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: jupyterlab
  type: LoadBalancer



