apiVersion: v1
kind: Pod
metadata:
  name: jupyterlab
  annotations:
    "k8s.aliyun.com/eci-with-eip": "true"
spec:
  containers:
    - image: registry-vpc.cn-shanghai.aliyuncs.com/wmn/cuda:jupyterlab # 训练任务的镜像
      name: jupyterlab


      resources:
        requests:
          cpu: 2
          memory: 8Gi
      ports:
        - containerPort: 8786
          name: scheduler-port
          protocol: TCP
        - containerPort: 8787
          name: dashboard
          protocol: TCP


